### ISSUE TITLE
Server Only Build

### ISSUE THREAD

**Issue by shredder2500** [vis2k/DOTSNET#33]
When building if I have clicked Server Build I would expect the client world to not be created at all. I currently have three Scenes to get around this. Client Only, Server Only, and Both (Development Scene) but the client world still gets created in the server only one with like 3 or 4 systems. 

I have been able to change this my self by adding #if UNITY_EDITOR || UNITY_SERVER around the create server world call in the bootstrap class, also changed Covert Network Entity so that it can handle server world being null.

Also would be nice to have Client only builds. maybe UNITY_CLIENT?

**Comment by crowder** [comment]
I'm seeing this also, additionally, when dependency injection runs, the code is trying to DI server systems into server system-groups that shouldn't exist on the client at all, and issuing warning messages that the server-system in question should not exist.

`ServerActiveSimulationGroup` is one such example.

**Comment by vis2k** [comment]
thanks, will look into it. should be useful indeed.

**Comment by vis2k** [comment]
done.
server builds will not update the client world anymore in next version.

for convenience, the client world still exists though.
otherwise we would need #if UNITY_SERVER checks all over the place: bootstrap, converttoentity, authoring, etc. 

a lot of authoring components have a one time Awake() call to ClientWorld.
let's keep it, but simply not update it.

ease of use!
